dist: xenial

language: python
python:
  - 3.6
  - 3.7
  - 3.8

cache:
  pip: true
  directories:
    - .venv

env:
  global:
    - RANDOM_SEED=0
  matrix:
    - FLASK_VERSION=1.1.1

before_install:
  - pip install pipenv

install:
  - make install

before_script:
  - pipenv run pip install flask==${FLASK_VERSION}

script:
  - make check
  - make test

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular

notifications:
  email:
    on_success: never
    on_failure: never
